In [1]:
#导入相关包
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from scipy import linalg

#plt.rcParams['font.sans-serif'] = 'simlei'
plt.rcParams ['axes.unicode_minus'] = False

# 1. 读取iris数据
iris = pd.read_csv('./data/iris.csv')

In [2]:
X = iris.values[:, 1:5].astype(np.float64)
y = iris.values[:, 5]

# 3.将特征数据标准化
X_std = StandardScaler().fit_transform(X)
print(X_std)

[[-9.00681170e-01  1.01900435e+00 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00 -1.31979479e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.38535265e+00  3.28414053e-01 -1.39706395e+00 -1.31544430e+00]
 [-1.50652052e+00  9.82172869e-02 -1.28338910e+00 -1.31544430e+00]
 [-1.02184904e+00  1.24920112e+00 -1.34022653e+00 -1.31544430e+00]
 [-5.37177559e-01  1.93979142e+00 -1.16971425e+00 -1.05217993e+00]
 [-1.50652052e+00  7.88807586e-01 -1.34022653e+00 -1.18381211e+00]
 [-1.02184904e+00  7.88807586e-01 -1.28338910e+00 -1.31544430e+00]
 [-1.74885626e+00 -3.62176246e-01 -1.34022653e+00 -1.31544430e+00]
 [-1.14301691e+00  9.82172869e-02 -1.28338910e+00 -1.44707648e+00]
 [-5.37177559e-01  1.47939788e+00 -1.28338910e+00 -1.31544430e+00]
 [-1.26418478e+00  7.88807586e-01 -1.22655167e+00 -1.31544430e+00]
 [-1.26418478e+00 -1.31979479e-01 -1.34022653e+00 -1.44707648e+00]
 [-1.87002413e+00 -1.31979479e-01 -1.51073881e+00 -1.44707648e+00]
 [-5.25060772e-02  2.16998818e+00 -1.45390138e+00 -1.31544430e

In [3]:
eig_values = s ** 2
eig_vectors = v.T

NameError: name 's' is not defined

In [ ]:
# 6.将特征值和特征向量一一对应
eig_pairs = [(np.abs(eig_values[i]), eig_vectors[:, i]) for i in range(len(eig_vectors))]
print(eig_pairs)

In [ ]:
#7.计算每个特征值占特征值总和的比重(%)
total = sum(eig_values)
var_exp = [(i / total) * 100 for i in sorted(eig_values, reverse = True)]
print(var_exp)

In [ ]:
# 8. 可视化分析,每个特征值的比重
fig, ax = plt.subplots()
var_exp = np.round(var_exp, 2)
name_list = ['var_exp[0]',' var_exp[1]', ' var_exp[2]',' var_exp[3]']
plt.bar(range(len(var_exp)), var_exp, color=['r', 'b', 'g'], tick_label = name_list)
for a, b in zip(range(len(var_exp)), var_exp):
    plt.text(a, b + 0.5, b, ha ='center', va = 'bottom')
    plt.xlabel('特征值')
    plt.ylabel('各个特征值所占比重(%)')
    plt.title('特征值占比图')
    plt.show ()

In [ ]:
# 9.提取前两个特征,输出投影矩阵W
matrix_w=np.hstack((eig_pairs[0][1].reshape(4,1), eig_pairs[1] [1]. reshape(4,1)))
print('投影矩阵 W:\n', matrix_w)

In [ ]:
# 10.计算
Y= X_std.dot(matrix_w)
print(Y)