In [1]:
import numpy as np
my_array = np.array([2,3,4,5,6,7,8,9])

print(my_array[2:])

[4 5 6 7 8 9]


In [2]:
import numpy as np
my_array = np.linspace(1,1,10)

print(my_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [3]:
import numpy as np
my_array = np.array([1,2,3])

print (my_array)

[1 2 3]


In [4]:
import numpy as np
my_array = np.arange(10,20,2)

print (my_array)

[10 12 14 16 18]


In [5]:
import numpy as np
my_array = np.array([2,3,4,5,6,7,8,9])

print(my_array[2:5])

[4 5 6]


In [6]:
import numpy as np
my_array = np.arange(5)

print (my_array)

[0 1 2 3 4]


In [8]:
import numpy as np

my_array = np.array([1.0, 5.55, 123, 0.567, 25.532])

print("输出：\n", np.around(my_array))

输出：
 [  1.   6. 123.   1.  26.]


In [9]:
import numpy as np
my_array = np.array([[1,2,3],[4,5,6]])

print("数组的shape是：\n",my_array.shape)

数组的shape是：
 (2, 3)


In [10]:
import numpy as np
my_array = np.linspace(1,1,10)

print(my_array)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [11]:
import numpy as np 
my_array = np.array([[1,2,3],[4,5,6]]) 

my_result = my_array.reshape(3,2) 

print (my_result)

[[1 2]
 [3 4]
 [5 6]]
